obstacle_range: 2.5
raytrace_range: 9.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.1
inflation_radius: 0.15

observation_sources: laser_scan_sensor 
#point_cloud_sensor

laser_scan_sensor: {sensor_frame: sensor, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: base_link, data_type: PointCloud, topic: scan, marking: true, clearing: true}